web:
  build: .
  command: php -S 0.0.0.0:8000 -t /var/www
  links:
    - db
  ports:
    - "8000:8000"
  volumes:
    - "./app:/var/www"

db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp